### ISSUE TITLE
Stimulus Plays too Quickly

### ISSUE THREAD

**Issue by triplem0814** [zhuangjun1981/retinotopic_mapping#10] opened 2019-06-10 19:30 UTC
So far, I have installed and run this whole program on two computers.  On one, it works just fine.  One the other, I will use Flashing Circle as an example.  The expected display time is 5.05 s but it runs at a much faster rate and finishes in 0.5 s.  This faster rate occurs for all stims.  Additionally, once the display is done, the psychopy gray window does not close unless I close the command prompt or CTRL+ALT+DEL.  I have checked all inputs, and they are the same between the two computers.  Any ideas on how to fix this, or might this be a problem with the way the computer interacts with psychopy?

**Comment by zhuangjun1981** [comment] 2019-06-10 22:56
I will first check your monitor display refresh rate in your video card settings. The `refresh_rate` variable in `Monitor` class should match that. Also if you can send me the script you ran, it will help me diagnose.

**Comment by triplem0814** [comment] 2019-06-11 13:18
Alright, I checked the refresh rates, and they match. Here is the script I ran:
`activate retinotopic_mapping
cd Anaconda2\envs\retinotopic_mapping\Lib\site-packages\retinotopic_mapping-2.8.0- 
                         py2.7.egg\retinotopic_mapping
python
from MonitorSetup import Monitor, Indicator
mon = Monitor(resolution=(1080,1920),
                  refresh_rate=60.,
                  mon_width_cm=90.,
                  mon_height_cm=50.,
                  dis=20,
                  C2T_cm=30.,
                  C2A_cm=40.)
ind = Indicator(mon)
import StimulusRoutines as stim
from DisplayStimulus import DisplaySequence
flashing_circle = stim.FlashingCircle(mon,ind)
ds = DisplaySequence(log_dir='log_directory')
ds.set_stim(flashing_circle)
ds.trigger_display()`
Although, I have tried other stimuli with the same results.

**Comment by triplem0814** [comment] 2019-06-11 13:19
That didn't really format like I thought it would.  I just ran the script in the Getting Started section of readthedocs.

**Comment by zhuangjun1981** [comment] 2019-06-11 17:07
1. Did you see the flash during your display?
2. Did the software save any log file in your "log_directory"
3. What does the console print after your display?

**Comment by triplem0814** [comment] 2019-06-11 17:41
1. Sometimes I will see the flashing circle, but sometimes, it is only a half-circle or non-existent.  The same is true for the indicator square. 
2. It did save a log file in that directory. 
3. I have attached a picture of the cmd output.

I am wondering if it has to do with what was already installed on the computer before I installed this.  The first computer I worked on had nothing on it.  This computer already had some of the dependencies already installed.  Maybe the configuration of those programs is messing something up.
![cmd](https://user-images.githubusercontent.com/40804489/59294108-a24ffe80-8c4e-11e9-91f9-368a9e8e2364.jpg)

**Comment by zhuangjun1981** [comment] 2019-06-11 20:12
This is helpful. It looks like the code is doing what it is supposed to do. The problem is just for some reason your system is displaying at a much faster rate. The reason you do not see a circle sometimes is probably because it is too fast.

A hackish way to fix that is you adjust the `refresh_rate` in `monitor` to match your real refresh rate (which looks like ~500 Hz !).

What worries me is the psychopy window does not close correctly. It may suggest that there maybe some problem between psychopy and your system. I would recommend to delete the current `retinotopic_mapping` environment. Then reinstall `retinotopic_mapping` package following the steps in the front page. It will automatically recreate `retinotopic_mapping` environment and install the correct psychopy package.

Also please pull the most recent master branch.

Jun

**Comment by triplem0814** [comment] 2019-06-11 20:27
Thank you. I am currently starting over from scratch by uninstalling python, the environment, and all the dependencies.  Hopefully, this will work. Thank you once again.

**Comment by triplem0814** [comment] 2019-06-12 17:55
It still is having the same problem.  We are going to try to wipe the entire computer to see if that will help.  Also, I noticed a message on the computer today that said DisplayPort Lower Setting Applied.  I looked into this to see if this may be causing the issue, but I am still unsure.

**Comment by zhuangjun1981** [comment] 2019-06-12 18:05
Well. Good luck. I may try to reinstall or update video card driver before wiping the entire computer. But it is up to you.

**Comment by zhuangjun1981** [comment] 2019-06-12 18:09
Also I have noticed in your image that you are using the default monitor resolution (1920x1080) from the package which does not match your system's (1280x1024).  It is better to set this resolution to your system's resolution. It is the `resolution` variable in the  `Monitor` class.

**Comment by triplem0814** [comment] 2019-06-12 18:11
I will try to update the video card driver, and I will change the monitor resolution. Thank you.

**Comment by triplem0814** [comment] 2019-06-13 13:31
I have now tried reinstalling the video card driver and erasing all the dependencies to no effect.  I also installed it on a brand new computer.  The speed problem is gone, but the window still does not close after the stimulus is done.  The first computer is a Dell Precision T7610 with an AMD FirePro W7000 (FireGL V) graphics card.  The second is a Dell Precision 5820 with an AMD Radeon Pro WX 2100 graphics card. Both are connected to their monitors through DisplayPort.  I don't know if this helps.  Just thought I would give you this extra info.

**Comment by zhuangjun1981** [comment] 2019-06-13 16:24
I believe this should be an psychopy issue. A simple test will be try just use psychopy:

```
import psychopy.visual as vis
win = vis.Window()
```
see if a psychopy window is poping up.
then try:
```
win.close()
```
see if it closes properly.

**Comment by triplem0814** [comment] 2019-06-13 18:14
That did close it, so I'm not sure what the problem is.

**Comment by zhuangjun1981** [comment] 2019-06-13 18:36
So you have installed it on three computers. One is totally fine, one displays superfast and does not close window, and one displays fine but does not close window?

**Comment by derricw** [comment] 2019-06-13 18:38
Try enabling vsync (vertical sync) in your graphics settings.

**Comment by zhuangjun1981** [comment] 2019-06-13 18:53
Thank you, Derric.

**Comment by triplem0814** [comment] 2019-06-13 20:19
Yep, that fixed the speed problem. Thank you.  The window closing problem still persists.

**Comment by zhuangjun1981** [comment] 2019-06-13 21:27
Great!
Now for the window not closing problem:

if you see "Display successfully completed." That means the psychopy window used for display should have already been closed properly. I just do not understand why there is still a window ...

**Comment by zhuangjun1981** [comment] 2019-06-17 18:32
I will close this for now. Looks like the window-not-closing problem is specific to just one system. If the similar problem happens in other systems, we will dig deeper into this.

**Closed by zhuangjun1981** 2019-06-17 18:32 UTC
